version: '3.3'

volumes:
  foodgram_pg_data:
  static:
  media:

services:
  backend:
    build: ../foodgram/
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/app/media/

  db:
    image: postgres:13.10

    env_file: ../.env

    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data



  frontend:
    image: saikal2003/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
