version: '3.3'

volumes:
  foodgram_pg_data2:
  static:
  media:

services:
  backend:
    image: saikal12/foodgram_backend
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - foodgram_pg_data2:/var/lib/postgresql/data



  frontend:
    image: saikal12/foodgram_frontend
    volumes:
      - static:/frontend_static
  nginx:
    image: saikal12/foodgram_gateway
    ports:
      - 9090:80
    volumes:
      - static:/static/
      - media:/var/html/media/

    depends_on:
      - backend