version: '3.3'

volumes:
  foodgram_pg_data:
  static:
  media:

services:
  backend:
    image: saikal12/foodgram_backend
    env_file: ../.env
    volumes:
      - static:/backend_static/
      - media:/app/media/

  db:
    image: postgres:13.10

    env_file: ../.env

    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data



  frontend:
    image: saikal12/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: saikal12/foodgram_gateway
    ports:
      - "9090:80"
    volumes:
      - static:/var/html/static/
      - media:/media/
