version: '3.3'

volumes:
  foodgram_pg_data:
  static:
  media:

services:
  backend:
    build: ../foodgram/
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  db:
    image: postgres:13.10

    env_file: ../.env

    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data


  frontend:
    build: ../frontend/
    volumes:
      - static:/frontend_static
  nginx:
    build: ../nginx/
    ports:
      - "9090:80"
    volumes:
      - static:/static/
      - media:/var/html/media/

    depends_on:
      - backend
